---
title: Experience
---

<!--

# Student PT - B Project

- January - May 2025


-->


# Stretch-Affect

- During my "clinical year" of physical therapy school, I had the privilege of working at <i>Stretch Affect</i>, a 
- 8 week PT internship
- Out-of-network outpatient Ortho
- Developing plans of care for patients
- Skills
    - Breathwork
    - Administering laser, cupping, estim, and NMES modalities
    - 3D screening using Kinotek
    - Assessing foot asymmetry and orthotic indication using the *footscan*.
- During my internship, Stretch Affect became the official recovery partner for the San Diego Mojo Pro Women's Volleyball team.
    - I was given the responsibility of creating programs on the Stretch Affect App to help guide the athletes around the equipment and to perform self-myofascial releases
    - There was 3 parts to the program: Trunk/low back, Lower extremity, and upper extremity.
- I presented an in-service on Dual-tasking, which was used to become a blog on the company website .
    - <a href="https://www.stretchaffect.com/blog/dual-task-training">Modified Stretch Affect blog</a>
    - <a href="https://yomokerst.com/The%20Archive/Neuroscience/Neurorehabilitation/dual_task.html">My presentation</a>

## SDSU Liftathon Eventg

During my Stretch Affect clinical, I was able to 

- November 16th 2024
- Prepare athletes for lifting
- Athlete recovery after event

# Kaiser Permanente Inpatient

- Kaiser Permanente in Irvine, CA 
-  Studied under the tutelage of Dr. Pia Hernandez 
- Internship as a Student physical therapist
- Inpatient physical therapy


# All Star PT Mira Mesa

- Internship as a Student physical therapist
- CI: Allen Maskell PT, DPT

In the summer of 2023, I was fortunate to work as a Student Physical Therapist at *All Star Physical Therapy* in Mira Mesa.
All Star PT is an in-network outpatient orthopedic physical therapy clinic.
Throughout my internship, I was able to learn how an in-network clinic is run and how to be both effective for my patients and a productive asset to the clinic.
I was able to treat a variety of post-operative conditions, notably complex foot surgeries and shoulder surgeries.
This is the first time I dealt with a patient experiencing post-op complication of hyperalgesia and through *pain neuroscience education* my CI and I were able to help this patient manage their pain and return to normal life.

# PT Tech - Seal Beach PT

2021-2022


